Enu.CMS/Controllers/SchoolController.cs
using System;
using Enu.Cms.BL;
using System.Web;
using ENU.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Data;


namespace ENU.CMS.Controllers
{
    public class SchoolController : Controller
    {
        IDataAccessor accessor;
        Member mem = new Member();


        [HttpGet]
        public ActionResult All()
        {
            try
            {
                mem.AuthenticateUser();


                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute;
                    institute = new Institute();
                    institute.InstituteType = "school";
                    DataTable dataTable = inst.GetAllInstitutes(institute);
                    var list = new List<Institute>(from a in dataTable.AsEnumerable()
                                                   select new Institute
                                                   {
                                                       Name = Convert.ToString(a["Name"]),
                                                       Phone1 = Convert.ToString(a["Phone1"]),
                                                       AffiliationName = Convert.ToString(a["Affliation"]),
                                                       Address = Convert.ToString(a["Address"])
                                                   });
                    return View(list);
                }

            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                {
                    ViewBag.Message = "ERR";
                }


                return View(new List<Institute>());
            }
        }


        [HttpGet]
        public ActionResult Add()
        {
            try
            {
                mem.AuthenticateUser();
                return View();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                {
                    ViewBag.Message = "ERR";
                    return View();
                }
            }
        }


        [HttpPost]
        public ActionResult Add(FormCollection frmObj)
        {
            try
            {
                mem.AuthenticateUser();

                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute = inst.School();
                    institute.Name = frmObj["institute_name"];
                    institute.Address = frmObj["institute_adr"];
                    institute.State = int.Parse(frmObj["institute_state"]);
                    institute.City = int.Parse(frmObj["institute_city"]);
                    institute.Country = int.Parse(frmObj["institute_country"]);
                    institute.Description = frmObj["institute_desc"];
                    institute.Phone1 = frmObj["institute_phone1"];
                    institute.Phone2 = frmObj["institute_phone2"];
                    institute.Email = frmObj["institute_email"];
                    institute.WebUrl = frmObj["institute_webUrl"];
                    institute.EstablishedOn = int.Parse(frmObj["institute_esht"]);
                    institute.AffiliationId = int.Parse(frmObj["institute_affliation"]);
                    institute.PinCode = "";
                    institute.Keywords = "";
                    institute.ImgUrl = "";
                    inst.Save(institute);
                }

                ViewBag.Message = "OK";
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }


        [HttpGet]
        public ActionResult Edit()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }
    }
}

Enu.CMS/Views/school/add.cshtml
@model ENU.CMS.ViewModel.InstitutionViewModel
@{
    ViewBag.Title = "ENU: Add new school";
    Layout = "~/Views/shared/EnuMember.cshtml";
}
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                Add New School</h3>
        </div>
        <div class="header-search">
        </div>
    </div>
    @using (Html.BeginForm("add", "school", FormMethod.Post, new { id = "formNewSchool" }))
    {
       
        <div class="page-header">
            <div id="errorMsg">
            </div>
            @{
        string blokDisplay = "none";
        if (ViewBag.Message == "OK")
        {
            blokDisplay = "block";
                <div class="alert alert-success"  style="display: @blokDisplay">
                    <strong>Success!</strong> Information saved successfully.
                </div>
        }
        else if (ViewBag.Message == "ERR")
        {
            blokDisplay = "block";
                <div class="alert alert-danger"  style="display: @blokDisplay">
                    <strong>Sorry!</strong> Failed to save your information. Please check the entered
                    data and try again!"
                </div>
        }
            }
            <div id="load_institution">
                <div class="panel">
                    <div class="panel-body">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>
                                        School Name:
                                    </th>
                                    <td>
                                        <input name="institute_name" maxlength="150" type="text" class="form-control required"
                                            data-friendly-name="School name" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Description:
                                    </th>
                                    <td>
                                        <textarea name="institute_desc" id="institute_desc" maxlength="1000" cols="30" rows="10"
                                            class="form-control" spellcheck="spellcheck"></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Primary Phone:
                                    </th>
                                    <td>
                                        <input name="institute_phone1" id="institute_phone1" min="0" max="9999999999" class="form-control required phone"
                                            data-friendly-name="Primary phone" type="number" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Secondary Phone:
                                    </th>
                                    <td>
                                        <input name="institute_phone2" id="institute_phone2" min="0" max="9999999999" class="form-control"
                                            type="number" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Eshtablisment Year:
                                    </th>
                                    <td>
                                        <input name="institute_esht" id="institute_esht" min="0" max="9999" class="form-control required"
                                            data-friendly-name="Establishment year" type="number" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Email:
                                    </th>
                                    <td>
                                        <input name="institute_email" id="institute_email" maxlength="80" class="form-control required email"
                                            data-friendly-name="Email id" type="email" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Web URL:
                                    </th>
                                    <td>
                                        <input name="institute_webUrl" id="institute_webUrl" maxlength="80" class="form-control"
                                            type="url" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Board:
                                    </th>
                                    <td>
                                        <select name="institute_affliation" id="institute_affliation" class="js-example-placeholder-single required"
                                            data-friendly-name="Board">
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Address:
                                    </th>
                                    <td>
                                        <input name="institute_adr" id="institute_adr" maxlength="150" type="text" class="form-control required"
                                            data-friendly-name="Address" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Country:
                                    </th>
                                    <td>
                                        <select name="institute_country" id="lst_country" class="js-example-placeholder-single required"
                                            data-friendly-name="Country">
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        State:
                                    </th>
                                    <td>
                                        <select name="institute_state" id="lst_state" class="js-example-placeholder-single required"
                                            data-friendly-name="State">
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        City:
                                    </th>
                                    <td>
                                        <select name="institute_city" id="lst_city" class="js-example-placeholder-single required"
                                            data-friendly-name="City">
                                        </select>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="btn-row" id="dic_post" style="display: block">
                <input type="button" value="Save School" class="btn btn-primary" onclick="enuManager.validateForm('#formNewSchool');" />
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="../assets/js/Loader.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        LoadBoardList('b')
        LoadCountry();
        LoadAllBoards();
    });
</script>

Enu.CMS/Views/school/all.cshtml
@model List<ENU.Entity.Institute>
@using GridMvc.Html
@{
    ViewBag.Title = "ENU:  All added schools";
    Layout = "~/Views/shared/EnuMember.cshtml";
}
<script src="@Url.Content("~/assets/js/jquery.min.js")" type="text/javascript"> </script>
<link href="@Url.Content("~/assets/css/Gridmvc.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/assets/js/gridmvc.min.js")" type="text/javascript"> </script>
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                All Added Schools</h3>
        </div>
        
        <div class="header-search">
            <a class="btn-add-new" href="/school/add">Add New</a>
        </div>
    </div>
    @Html.Grid(Model).Columns(columns =>
           {
               columns.Add(c => c.Name).Titled("NAME");
               columns.Add(c => c.Address).Titled("ADDRESS").Filterable(true);
               columns.Add(c => c.AffiliationName).Titled("AFFILIATION").Filterable(true);
               columns.Add(c => c.Phone1).Titled("PHONE").Filterable(true);
               columns.Add().Encoded(false).Sanitized(false).RenderValueAs(c => Html.ActionLink("Edit", "Edit", "School", new { id = c.Name }, null)).Titled("");
           }).WithPaging(10).Sortable(true)
</div>