Enu.CMS/Controllers/ScController.cs
using System;
using Enu.Cms.BL;
using System.Web;
using ENU.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Data;


namespace ENU.CMS.Controllers
{
    public class ScController : Controller
    {
        IDataAccessor accessor;
        Member mem = new Member();

        [HttpGet]
        public ActionResult All()
        {
            try
            {
                mem.AuthenticateUser();


                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute;
                    institute = new Institute();
                    institute.InstituteType = "Tution Centre";
                    DataTable dataTable = inst.GetAllInstitutes(institute);
                    var list = new List<Tution_Centre>(from a in dataTable.AsEnumerable()
                                                       select new Tution_Centre
                                                   {
                                                       Name = Convert.ToString(a["Name"]),
                                                       Phone1 = Convert.ToString(a["Phone1"]),
                                                       Phone2 = Convert.ToString(a["Phone2"]),
                                                       Email = Convert.ToString(a["Email"]),
                                                       Address = Convert.ToString(a["Address"]),
                                                       EstablishedOn = Convert.ToInt32(a["EstablishmentYear"])
                                                   });
                    return View(list);
                }

            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                {
                    ViewBag.Message = "ERR";
                }


                return View(new List<Institute>());
            }
        }


        [HttpGet]
        public ActionResult Add()
        {
            try
            {
                mem.AuthenticateUser();
                return View();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                {
                    ViewBag.Message = "ERR";
                    return View();
                }
            }
        }


        [HttpPost]
        public ActionResult Add(FormCollection frmObj)
        {
            try
            {
                mem.AuthenticateUser();

                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute = inst.TutionCentre();
                    institute.Name = frmObj["institute_name"];
                    institute.Address = frmObj["institute_adr"];
                    institute.State = int.Parse(frmObj["institute_state"]);
                    institute.City = int.Parse(frmObj["institute_city"]);
                    institute.Country = int.Parse(frmObj["institute_country"]);
                    institute.Description = frmObj["institute_desc"];
                    institute.Phone1 = frmObj["institute_phone1"];
                    institute.Phone2 = frmObj["institute_phone2"];
                    institute.Email = frmObj["institute_email"];
                    institute.WebUrl = frmObj["institute_webUrl"];
                    institute.EstablishedOn = int.Parse(frmObj["institute_esht"]);
                    //institute.AffiliationId = int.Parse(frmObj["institute_affliation"]);
                    institute.PinCode = frmObj["institute_pincode"];
                    institute.Keywords = "";
                    institute.ImgUrl = "";
                    inst.Save(institute);
                }

                ViewBag.Message = "OK";
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }


        [HttpGet]
        public ActionResult Edit()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }
    }
}

Enu.CMS/Views/sc/add.cshtml
@model ENU.CMS.ViewModel.InstitutionViewModel
@{
    ViewBag.Title = "ENU: Add new study centre";
    Layout = "~/Views/shared/EnuMember.cshtml";
}
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                Add New Study Centre</h3>
        </div>
        <div class="header-search">
        </div>
    </div>
    @using (Html.BeginForm("add", "sc", FormMethod.Post, new { id = "formNewSchool" }))
    {
       
        <div class="page-header">
            <div id="errorMsg">
            </div>
            @{
        string blokDisplay = "none";
        if (ViewBag.Message == "OK")
        {
            blokDisplay = "block";
                <div class="alert alert-success"  style="display: @blokDisplay">
                    <strong>Success!</strong> Information saved successfully.
                </div>
        }
        else if (ViewBag.Message == "ERR")
        {
            blokDisplay = "block";
                <div class="alert alert-danger"  style="display: @blokDisplay">
                    <strong>Sorry!</strong> Failed to save your information. Please check the entered
                    data and try again!"
                </div>
        }
            }
            <div id="load_institution">
                <div class="panel">
                    <div class="panel-body">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>
                                        Study Centre Name:
                                    </th>
                                    <td colspan="3">
                                        <input name="institute_name" maxlength="150" type="text" class="form-control required"
                                            data-friendly-name="Study Centre Name" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Description:
                                    </th>
                                    <td colspan="3">
                                        <textarea name="institute_desc" id="institute_desc" maxlength="1000" cols="30" rows="5"
                                            class="form-control" spellcheck="spellcheck"></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Targeted Courses:
                                    </th>
                                    <td colspan="3">
                                        <input name="institute_affliation" id="institute_affliation" maxlength="150" class="form-control required"
                                            data-friendly-name="Targeted Courses" spellcheck="spellcheck" />
                                    </td>
                                </tr>
                                <tr>
                                    <th width="20%">
                                        Classes:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_classes" id="institute_classes" min="0" max="9999999999" class="form-control required"
                                            data-friendly-name="Classes" type="text" />
                                    </td>
                                    <th width="20%">
                                        Running From:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_esht" id="institute_esht" min="0" max="9999" class="form-control required"
                                            data-friendly-name="Running From" type="number" />
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        CONTACT DETAILS:
                                    </th>
                                    <td colspan="4">
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Address:
                                    </th>
                                    <td colspan="3">
                                        <input name="institute_adr" id="institute_adr" maxlength="150" type="text" class="form-control required"
                                            data-friendly-name="Address" />
                                    </td>
                                </tr>
                                <tr>
                                    <th width="20%">
                                        Primary Phone:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_phone1" id="institute_phone1" min="0" max="9999999999" class="form-control required phone"
                                            data-friendly-name="Primary Phone" type="number" />
                                    </td>
                                    <th width="20%">
                                        Secondary Phone:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_phone2" id="institute_phone2" min="0" max="9999999999" class="form-control"
                                            type="number" />
                                    </td>
                                </tr>
                                <tr>
                                    <th width="20%">
                                        Email:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_email" id="institute_email" maxlength="80" class="form-control required email"
                                            data-friendly-name="Email" type="email" />
                                    </td>
                                    <th width="20%">
                                        Web URL:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_webUrl" id="institute_webUrl" maxlength="80" class="form-control"
                                            type="url" />
                                    </td>
                                </tr>
                                <tr>
                                    <th width="20%">
                                        Country:
                                    </th>
                                    <td width="30%">
                                        <select name="institute_country" id="lst_country" class="js-example-placeholder-single required"
                                            data-friendly-name="Country">
                                        </select>
                                    </td>
                                    <th width="20%">
                                        State:
                                    </th>
                                    <td width="30%">
                                        <select name="institute_state" id="lst_state" class="js-example-placeholder-single required"
                                            data-friendly-name="State">
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <th width="20%">
                                        City:
                                    </th>
                                    <td width="30%">
                                        <select name="institute_city" id="lst_city" class="js-example-placeholder-single required"
                                            data-friendly-name="City">
                                        </select>
                                    </td>
                                    <th width="20%">
                                        Postal Code:
                                    </th>
                                    <td width="30%">
                                        <input name="institute_pincode" id="institute_pincode" maxlength="6" type="text"
                                            class="form-control required" data-friendly-name="Postal Code" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="btn-row" id="dic_post" style="display: block">
                <input type="button" value="Save School" class="btn btn-primary" onclick="enuManager.validateForm('#formNewSchool');" />
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="../assets/js/Loader.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //LoadBoardList('b')
        LoadCountry();
        //LoadAllBoards();
    });
</script>

Enu.CMS/Views/sc/all.cshtml
@model List<ENU.Entity.Tution_Centre>
@using GridMvc.Html
@{
    ViewBag.Title = "ENU:  All added study centre";
    Layout = "~/Views/shared/EnuMember.cshtml";
}
<script src="@Url.Content("~/assets/js/jquery.min.js")" type="text/javascript"> </script>
<link href="@Url.Content("~/assets/css/Gridmvc.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/assets/js/gridmvc.min.js")" type="text/javascript"> </script>
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                All Added Study Centre</h3>
        </div>
        <div class="header-search">
            <a class="btn-add-new" href="/sc/add">Add New</a>
        </div>
    </div>
    @Html.Grid(Model).Columns(columns =>
           {
               columns.Add(c => c.Name).Titled("CENTRE NAME");
               columns.Add(c => c.Address).Titled("ADDRESS").Filterable(true);
               columns.Add(c => c.Phone1).Titled("CONTACTS").Filterable(true);
               columns.Add(c => c.Email).Titled("EMAIL").Filterable(true);
               columns.Add(c => c.EstablishedOn).Titled("RUNNING FROM").Filterable(true);
               columns.Add().Encoded(false).Sanitized(false).RenderValueAs(c => Html.ActionLink("Edit", "Edit", "Sc", new { id = c.Name }, null)).Titled("");
           }).WithPaging(10).Sortable(true)
</div>