Enu.CMS/Controllers/MemController.cs
using System;
using ENU.Entity;
using Enu.Cms.BL;
using System.Web;
using System.Web.Mvc;
using ENU.CMS.ViewModel;
using ENU.Entity.Common;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Data;

namespace ENU.CMS.Controllers
{
    public class MemController : Controller
    {
        IDataAccessor accessor;
        Member mem = new Member();

        [HttpGet]
        public ActionResult Dashboard()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }

        [HttpGet]
        public ActionResult Institutions()
        {
            //InstitutionType insType = new InstitutionType();

            try
            {
                mem.AuthenticateUser();


                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute;
                    institute = new Institute();
                    institute.InstituteType = "school";
                    DataTable dataTable = inst.GetAllInstitutes(institute);
                    var list = new List<Institute>(from a in dataTable.AsEnumerable()
                                                   select new Institute { Name = a["Name"].ToString(), Description = a["Desc"].ToString() });
                    return View(list);
                }               

            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                {
                    ViewBag.Message = "ERR";
                }


                return View(new List<Institute>());
            }
        }

        [HttpGet]
        public ActionResult AddInstitution()
        {
            try
            {
                mem.AuthenticateUser();
                return View();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                {
                    ViewBag.Message = "ERR";
                    return View();
                }
            }
        }


        [HttpGet]
        public ActionResult Logout()
        {
            if (Session["ticket"] != null)
            {
                accessor = new DataAccessor();
                IUserAuthentication ua = accessor.GetUserAuthentication();
                ua.Logout(string.Empty);
            }

            return mem.LogoutUser();
        }


        public PartialViewResult GetInstituitonView(int categoryId)
        {
            var model = new InstitutionViewModel();
            string viewName = string.Empty;
            switch (categoryId)
            {
                case 1:
                    viewName = "~/Views/Mem/components/School.cshtml";
                    break;
                case 2:
                    viewName = "~/Views/Mem/components/College.cshtml";
                    break;
                case 3:
                    viewName = "~/Views/Mem/components/TutionCentre.cshtml";
                    break;
                default:
                    viewName = "~/Views/Mem/components/School.cshtml";
                    break;
            }
            return PartialView(viewName, GetInstitutionViewModel());
        }


        [HttpPost]
        public ActionResult AddInstitution(FormCollection frmObj)
        {
            try
            {
                mem.AuthenticateUser();

                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute;

                    if (frmObj["institute_type"].ToLower() == "school")
                        institute = inst.School();
                    else if (frmObj["institute_type"].ToLower() == "college")
                        institute = inst.College();
                    else if (frmObj["institute_type"].ToLower() == "tution centre")
                        institute = new Tution_Centre();
                    else
                        institute = new Institute();

                    institute.Name = frmObj["institute_name"];
                    institute.Address = frmObj["institute_adr"];
                    institute.State = int.Parse(frmObj["institute_state"]);
                    institute.City = int.Parse(frmObj["institute_city"]);
                    institute.Country = int.Parse(frmObj["institute_country"]);
                    institute.Description = frmObj["institute_desc"];
                    institute.Phone1 = frmObj["institute_phone1"];
                    institute.Phone2 = frmObj["institute_phone2"];
                    institute.Email = frmObj["institute_email"];
                    institute.WebUrl = frmObj["institute_webUrl"];
                    institute.EstablishedOn = int.Parse(frmObj["institute_esht"]);
                    institute.AffiliationId = int.Parse(frmObj["institute_affliation"]);
                    institute.PinCode = "";
                    institute.Keywords = "";
                    institute.ImgUrl = "";
                    inst.Save(institute);
                }

                ViewBag.Message = "OK";
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View(GetInstitutionViewModel());
        }


        //TODO Later on it will have another filter like Active and all 
        [HttpGet]
        public JsonResult GetInstitution(string instituteType)
        {
            try
            {
                mem.AuthenticateUser();

                using (accessor = new DataAccessor())
                {
                    IInstitution inst = accessor.GetInstitution();
                    Institute institute;
                    //String instituteType = "school";
                    institute = new Institute();
                    //TODO Need to discuss view model implemetaation with Pandit 
                    //Pandit ceck this
                    institute.InstituteType = instituteType;
                    var dataTable = inst.GetAllInstitutes(institute);
                    //return View(dataTable);
                    //  return  JsonConvert.SerializeObject(ModelMapper.ConvertDataTable<InsititueViewModel>(dataTable), Formatting.Indented);
                    return Json(ModelMapper.ConvertDataTable<InsititueViewModel>(dataTable), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    Session.Clear();
                    return Json("", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    ViewBag.Message = "ERR";
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
        }


        [HttpGet]
        public ActionResult AddUser()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }


        [HttpPost]
        public ActionResult AddUser(FormCollection fromObj)
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }

        [HttpGet]
        public ActionResult AllUsers()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }


        private InstitutionViewModel GetInstitutionViewModel()
        {
            var model = new InstitutionViewModel();
            using (accessor = new DataAccessor())
            {
                IMasterDataHelper masterDataHelper = accessor.GetMasterDataHelper();
                IInstitution inst = accessor.GetInstitution();
                model.EnuCategories = (List<EnuCategories>)masterDataHelper.GetEnuCategories();

                model.Cities = (List<City>)masterDataHelper.GetAllCity(0);
                model.States = (List<State>)masterDataHelper.GetAllState(81);
                model.Countries = (List<Country>)masterDataHelper.GetAllCountry();
            }

            return model;
        }


        [HttpGet]
        public ActionResult Tutorial()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Tutorial(FormCollection frmObj, HttpPostedFileBase tutorial_file)
        {
            return View();
        }
    }
}

Enu.CMS/Controllers/TutorialController.cs
using System;
using System.Web;
using Enu.Cms.BL;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;

namespace ENU.CMS.Controllers
{
    public class TutorialController : Controller
    {
        IDataAccessor accessor;
        Member mem = new Member();

        [HttpGet]
        public ActionResult Add()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }


        [HttpPost]
        public ActionResult Add(FormCollection frmObj, HttpPostedFileBase tutorial_file)
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }

        [HttpGet]
        public ActionResult All()
        {
            try
            {
                mem.AuthenticateUser();
            }
            catch (Exception ex)
            {
                if (ex.Message.Equals("UNKOWN_USER"))
                {
                    return mem.LogoutUser();
                }
                else
                    ViewBag.Message = "ERR";
            }

            return View();
        }
    }
}

Enu.CMS/Views/mem/AddInstitution.cshtml
@model ENU.CMS.ViewModel.InstitutionViewModel
@{
    ViewBag.Title = "ENU: Add new institution";
    Layout = "~/Views/mem/EnuMember.cshtml";
}
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                Add New Institution</h3>
        </div>
        <div class="header-search">
            <input type="search" value="" />
            <input type="submit" value="Search Schools" class="btn" />
        </div>
    </div>
    @using (Html.BeginForm("addinstitution", "mem", FormMethod.Post, new { id = "formNewSchool" }))
    {
        <div class="page-header">
            <div class="page-header">
                <div class="page-title">
                    <h3 class="">
                    </h3>
                </div>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th style="width: 20%">
                                    Type of institution:
                                </th>
<<<<<<< HEAD
                                <td style="width: 80%">
                                    <select name="institute_type" id="institute_type" class="js-example-placeholder-single required"
                                        data-friendly-name="Board">
                                    </select>
                                    @*@Html.DropDownList("institute_type", new SelectList(Model.EnuCategories, "CategoryName", "CategoryName"), new { @class = "js-example-placeholder-single" })*@
=======
                                <td style="width: 80%">                                                             
                                    @Html.DropDownList("institute_type", new SelectList(Model.EnuCategories, "CategoryId", "CategoryName"), new { @class = "js-example-placeholder-single" })
>>>>>>> 99e95b7126d657abceabdab2031b233c1a5bc83a
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="page-header">
            <div class="page-header">
                <div class="page-title">
                    <h3 class="">
                    </h3>
                </div>
            </div>
            <div id="errorMsg">
            </div>
            @{
        string blokDisplay = "none";
        if (ViewBag.Message == "OK")
        {
            blokDisplay = "block";
                <div class="alert alert-success"  style="display: @blokDisplay">
                    <strong>Success!</strong> Information saved successfully.
                </div>
        }
        else if (ViewBag.Message == "ERR")
        {
            blokDisplay = "block";
                <div class="alert alert-danger"  style="display: @blokDisplay">
                    <strong>Sorry!</strong> Failed to save your information. Please check the entered
                    data and try again!"
                </div>
        }
            }
            <div id="load_institution">
            </div>
            <div class="btn-row" id="dic_post" style="display: none">
                <input type="button" value="Submit Form" class="btn btn-primary" onclick="enuManager.validateForm('#formNewSchool');" />
                <input type="submit" value="Cancel" id="Cancel" class="btn btn-danger" />
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="../assets/js/Loader.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
<<<<<<< HEAD
        LoadInstitution();
    });
=======
        $("[name=institute_type]").change(function () {
            $.ajax({
                type: 'GET',
                contentType: 'application/html; charset=utf-8',
                url: '@Url.Content("~/mem/GetInstituitonView")',
                dataType: 'html',
                data: {
                    categoryId: $("[name=institute_type]").val()
                },
                success: function (result) {
                    $("#load_institution").html(result);
                    $("#dic_post").show();
                    $(".alert").html('');
                    $(".alert").hide();
                }
            });
        });
    });   
>>>>>>> 99e95b7126d657abceabdab2031b233c1a5bc83a
</script>

Enu.CMS/Views/mem/AddUser.cshtml
@{
    ViewBag.Title = "ENU: Add new user";
    Layout = "~/Views/mem/EnuMember.cshtml";
}
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                Add New User</h3>
        </div>
        <div class="header-search">
            <input type="search" value="" />
            <input type="submit" value="Search Schools" class="btn" />
        </div>
    </div>
</div>

Enu.CMS/Views/mem/AllUsers.cshtml
@{
    ViewBag.Title = "ENU: All users";
    Layout = "~/Views/mem/EnuMember.cshtml";
}
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                All Users</h3>
        </div>
        <div class="header-search">
            <input type="search" value="" />
            <input type="submit" value="Search Schools" class="btn" />
        </div>
    </div>
</div>

Enu.CMS/Views/mem/Dashboard.cshtml
@{
    ViewBag.Title = "ENU: Dashboard";
    Layout = "/Views/shared/EnuMember.cshtml";
}
<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                Dashboard</h3>
        </div>
        <div class="header-search">
            <input type="search" value="" />
            <input type="submit" value="Search Schools" class="btn" />
        </div>
    </div>
    <div id="statistics-row-one" class="clearfix">
        <div class="card-box-col">
            <div class="x-card-box-inner">
                <p>
                    Users</p>
                <h2>
                    34578</h2>
                <p>
                    Last: 30.4k</p>
            </div>
        </div>
        <div class="card-box-col">
            <div class="x-card-box-inner">
                <p>
                    Reviews</p>
                <h2>
                    34578</h2>
                <p>
                    Last: 30.4k</p>
            </div>
        </div>
        <div class="card-box-col">
            <div class="x-card-box-inner">
                <p>
                    Schools</p>
                <h2>
                    34578</h2>
                <p>
                    Last: 30.4k</p>
            </div>
        </div>
        <div class="card-box-col">
            <div class="x-card-box-inner">
                <p>
                    Colleges</p>
                <h2>
                    34578</h2>
                <p>
                    Last: 30.4k</p>
            </div>
        </div>
        <div class="card-box-col">
            <div class="x-card-box-inner">
                <p>
                    Institute</p>
                <h2>
                    34578</h2>
                <p>
                    Last: 30.4k</p>
            </div>
        </div>
        <div class="card-box-col">
            <div class="x-card-box-inner">
                <p>
                    Home Tuition</p>
                <h2>
                    34578</h2>
                <p>
                    Last: 30.4k</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Heading Here
                    </h4>
                </div>
                <div class="panel-body">
                    Content here
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Heading Here
                    </h4>
                </div>
                <div class="panel-body">
                    Content here
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Heading Here
                    </h4>
                </div>
                <div class="panel-body">
                    Content here
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Heading Here
                    </h4>
                </div>
                <div class="panel-body">
                    Content here
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Heading Here
                    </h4>
                </div>
                <div class="panel-body">
                    Content here
                </div>
            </div>
        </div>
    </div>
</div>

Enu.CMS/Views/mem/Institutions.cshtml
@model List<ENU.Entity.Institute>
@using GridMvc.Html
@{
    ViewBag.Title = "ENU:  All added schools";
    Layout = "~/Views/mem/EnuMember.cshtml";
}
<script src="@Url.Content("~/assets/js/jquery.min.js")" type="text/javascript"> </script>
<link href="@Url.Content("~/assets/css/Gridmvc.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/assets/js/gridmvc.min.js")" type="text/javascript"> </script>
@Html.Grid(Model).Columns(columns =>
           {
               columns.Add(c => c.Name).Titled("Name");
               columns.Add(c => c.Description).Titled("Description").Filterable(true);
               columns.Add().Encoded(false).Sanitized(false).RenderValueAs(c => Html.ActionLink("Edit", "Edit", "Mem", new { id = c.Name }, null)).Titled("Action");
           }).WithPaging(10).Sortable(true); 
           
@*<div class="content-wrapper">
    <div class="page-header">
        <div class="page-title">
            <h3 class="">
                All Added Institutions</h3>
        </div>
        <div class="header-search">
            <input type="search" value="">
            <input type="submit" value="Search Schools" class="btn">
        </div>
    </div>
    @using (Html.BeginForm("addinstitution", "mem", FormMethod.Post))
    {
        <div class="page-header">
            <div class="page-header">
                <div class="page-title">
                    <h3 class="">
                    </h3>
                </div>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th style="width: 20%">
                                    Type of institution:
                                </th>
                                <td style="width: 80%">
                                    <select name="institute_type" id="institute_type" class="js-example-placeholder-single">
                                        <option selected="selected">Select One</option>
                                        <option>School</option>
                                        <option>College</option>
                                        <option>Tution Centre</option>
                                    </select>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="page-header">
            <div class="page-header">
                <div class="page-title">
                    <h3 class="">
                    </h3>
                </div>
            </div>
            <div id="errorMsg">
            </div>
            @{
        string blokDisplay = "none";
        if (ViewBag.Message == "OK")
        {
            blokDisplay = "block";
                <div class="alert alert-success" style="display: @blokDisplay">
                    <strong>Success!</strong> School information saved successfully.
                </div>
        }
        else if (ViewBag.Message == "ERR")
        {
            blokDisplay = "block";
                <div class="alert alert-danger" style="display: @blokDisplay">
                    <strong>Danger!</strong> Failed to save school information. Please check the entered
                    data and try again!"
                </div>
        }
            }
            <div class="btn-row" id="dic_post" style="display: none">
                <input type="submit" value="Submit Form" class="btn btn-primary" />
                <input type="submit" value="Cancel" class="btn btn-danger" />
            </div>
            <table id="institutions" class="table display nowrap dataTable dtr-inline">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            State
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Phone
                        </th>
                        <th>
                            Created
                        </th>
                        <th>
                            IsActive
                        </th>
                    </tr>
                </thead>
            </table>
        </div>
        
    }
</div>*@ @*http://paramquery.com/tutorial*@